# Generated by Django 2.2.1 on 2019-06-30 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='org',
            new_name='team',
        ),
        migrations.RemoveField(
            model_name='user',
            name='display_name',
        ),
    ]
